// Math accuracy suite: thousands of cases generated by
// tool/gen_accuracy_cases.py with mpmath / exact fractions as the oracle.
//
// Regenerate the data with:
//   python tool/gen_accuracy_cases.py
//
// Run from the package root (the JSON is loaded relative to the CWD):
//   dart test test/accuracy_test.dart
@Timeout(Duration(minutes: 5))
library;

import 'dart:convert';
import 'dart:io';
import 'dart:math' as math;

import 'package:math_engine/math_engine.dart';
import 'package:test/test.dart';

const engine = DefaultMathEngine();

final runKnown = Platform.environment['ACCURACY_KNOWN'] == '1';

/// A decimal number in normalized form: `±0.d1d2d3… × 10^(exp+1)`, i.e. the
/// first digit has weight 10^exp. `digits` has no trailing zeros.
class NormNum {
  NormNum(this.negative, this.digits, this.exp);

  static final zero = NormNum(false, '', 0);

  final bool negative;
  final String digits;
  final int exp;

  bool get isZero => digits.isEmpty;

  /// Parses `0`, `[-]D.DDDE<exp>`, `[-]DDD.DDD`, `[-]DDDE<exp>` …
  factory NormNum.parse(String s) {
    var t = s.trim();
    var neg = false;
    if (t.startsWith('-')) {
      neg = true;
      t = t.substring(1);
    }
    var e = 0;
    final ei = t.indexOf('E');
    if (ei >= 0) {
      e = int.parse(t.substring(ei + 1));
      t = t.substring(0, ei);
    }
    final dot = t.indexOf('.');
    final intPart = dot >= 0 ? t.substring(0, dot) : t;
    final fracPart = dot >= 0 ? t.substring(dot + 1) : '';
    var all = intPart + fracPart;
    // weight of the first character of `all` is 10^(intPart.length-1+e)
    var firstExp = intPart.length - 1 + e;
    var k = 0;
    while (k < all.length && all[k] == '0') {
      k++;
    }
    all = all.substring(k);
    firstExp -= k;
    all = all.replaceFirst(RegExp(r'0+$'), '');
    if (all.isEmpty) return zero;
    return NormNum(neg, all, firstExp);
  }

  /// Canonical text, identical to the Python generator's `norm_real`.
  String get canonical {
    if (isZero) return '0';
    final m = digits.length == 1 ? digits : '${digits[0]}.${digits.substring(1)}';
    return '${negative ? '-' : ''}${m}E$exp';
  }

  /// Signed mantissa in [1, 10) as a double.
  double get mantissa {
    if (isZero) return 0;
    final d = digits.length > 18 ? digits.substring(0, 18) : digits;
    final v = double.parse(d.length == 1 ? d : '${d[0]}.${d.substring(1)}');
    return negative ? -v : v;
  }

  /// Value divided by 10^scale, as a double (underflows gracefully to 0).
  double scaled(int scale) {
    if (isZero) return 0;
    final shift = exp - scale;
    if (shift < -330) return 0;
    if (shift > 330) return mantissa.sign * double.infinity;
    return mantissa * math.pow(10.0, shift);
  }

  @override
  String toString() => canonical;
}

String _fmt(Num n, int digits) => NumberFormatter(FormatOptions(
      digits: digits,
      fraction: FractionMode.decimal,
      notation: NumberNotation.scientific,
    )).format(n).plain;

/// Engine number rounded to [digits] significant digits, normalized.
NormNum normOf(Num n, [int digits = 25]) => n.isZero ? NormNum.zero : NormNum.parse(_fmt(n, digits));

/// |a − b| ≤ rel·|b| or |a − b| ≤ absTol (with b the expected value).
/// When [scaleRef] is given the relative bound uses 10^scaleRef·rel instead
/// (complex parts are compared relative to |z|).
bool close(NormNum a, NormNum b, double rel, double absTol, {int? scaleRef}) {
  final scale = scaleRef ?? (b.isZero ? (a.isZero ? 0 : a.exp) : b.exp);
  final av = a.scaled(scale), bv = b.scaled(scale);
  final diff = (av - bv).abs();
  final ref = scaleRef != null ? 1.0 : bv.abs();
  if (diff <= rel * ref) return true;
  // absolute check in real units
  final absDiff = scale > 300 ? double.infinity : diff * math.pow(10.0, scale);
  return absDiff <= absTol;
}

String describe(Value v) {
  switch (v) {
    case NumberValue(:final n):
      if (n is Cpx) return '${_fmt(n.re, 25)} + (${_fmt(n.im, 25)})i';
      final kind = n is Rat ? 'Rat' : 'Dec';
      final extra = n is Rat && !(n.d == BigInt.one) ? ' (= ${n.n}/${n.d})' : '';
      return '$kind ${_fmt(n, 25)}$extra';
    case MatrixValue(:final rows):
      return 'Matrix ${rows.map((r) => r.map(_exactText).toList()).toList()}';
    case BoolValue(:final value):
      return 'Bool $value';
    default:
      return '${v.runtimeType} $v';
  }
}

String _exactText(Num n) {
  if (n is Rat) return n.d == BigInt.one ? '${n.n}' : '${n.n}/${n.d}';
  return 'inexact(${_fmt(n, 20)})';
}

AngleMode angleOf(String s) => switch (s) {
      'deg' => AngleMode.deg,
      'rad' => AngleMode.rad,
      'grad' => AngleMode.grad,
      _ => throw ArgumentError(s),
    };

void check(Map<String, dynamic> c) {
  final expr = c['expr'] as String;
  final settings = CalcSettings(
    precision: c['precision'] as int,
    angleMode: angleOf(c['angle'] as String),
    complexResults: (c['complex'] as bool?) ?? false,
  );
  final kind = c['kind'] as String;
  final r = engine.evaluate(expr, settings, Environment());
  final ctx = '$expr  [${c['angle']}, precision ${c['precision']}'
      '${settings.complexResults ? ', complex' : ''}]';

  if (kind == 'error') {
    switch (r) {
      case Failure(:final error):
        expect(error.code.name, c['error'], reason: ctx);
      case Success(:final value):
        fail('$ctx: expected error ${c['error']} but got ${describe(value.value)}');
      case Cancelled():
        fail('$ctx: cancelled');
    }
    return;
  }

  final Value value;
  switch (r) {
    case Success(value: final ev):
      value = ev.value;
    case Failure(:final error):
      fail('$ctx: unexpected error ${error.code.name}: ${error.message}');
    case Cancelled():
      fail('$ctx: cancelled');
  }

  switch (kind) {
    case 'exact':
      if (value is! NumberValue || value.n is! Rat) {
        fail('$ctx: expected exact ${c['expect']}, got ${describe(value)}');
      }
      expect(_exactText(value.n), c['expect'], reason: ctx);
    case 'bool':
      if (value is! BoolValue) fail('$ctx: expected bool, got ${describe(value)}');
      expect('${value.value}', c['expect'], reason: ctx);
    case 'matrix':
      if (value is! MatrixValue) fail('$ctx: expected matrix, got ${describe(value)}');
      final got = value.rows.map((row) => row.map(_exactText).toList()).toList();
      final want = (c['expect'] as List).map((row) => (row as List).cast<String>().toList()).toList();
      expect(got, want, reason: ctx);
    case 'real':
      if (value is! NumberValue || value.n is Cpx) fail('$ctx: expected real, got ${describe(value)}');
      final want = NormNum.parse(c['expect'] as String);
      final got = normOf(value.n);
      final ok = close(got, want, (c['rel_tol'] as num).toDouble(), (c['abs_tol'] as num).toDouble());
      if (!ok) fail('$ctx\n  expected ${want.canonical}\n  got      ${describe(value)}');
    case 'complex':
      if (value is! NumberValue) fail('$ctx: expected complex, got ${describe(value)}');
      final n = value.n;
      final re = n is Cpx ? n.re : n;
      final im = n is Cpx ? n.im : Rat.zero;
      final parts = (c['expect'] as String).split('|');
      final wr = NormNum.parse(parts[0]), wi = NormNum.parse(parts[1]);
      final gr = normOf(re), gi = normOf(im);
      // Tolerance relative to |z| (scale by the larger exponent).
      final refExp = [if (!wr.isZero) wr.exp, if (!wi.isZero) wi.exp].fold<int?>(null, (m, e) => m == null ? e : math.max(m, e));
      final rel = (c['rel_tol'] as num).toDouble(), absTol = (c['abs_tol'] as num).toDouble();
      final ok = refExp == null
          ? close(gr, wr, rel, absTol) && close(gi, wi, rel, absTol)
          : close(gr, wr, rel, absTol, scaleRef: refExp) && close(gi, wi, rel, absTol, scaleRef: refExp);
      if (!ok) {
        fail('$ctx\n  expected ${wr.canonical} + (${wi.canonical})i\n  got      ${describe(value)}');
      }
    case 'digits':
      if (value is! NumberValue || value.n is Cpx) fail('$ctx: expected real, got ${describe(value)}');
      final nd = c['digits'] as int;
      final got = normOf(value.n, nd).canonical;
      expect(got, c['expect'], reason: '$ctx (first $nd significant digits)');
    default:
      fail('unknown kind $kind');
  }
}

void main() {
  final file = File('test/data/accuracy_cases.json');
  final cases = (jsonDecode(file.readAsStringSync(encoding: utf8)) as List).cast<Map<String, dynamic>>();

  test('case file is populated', () {
    expect(cases.length, greaterThan(1000));
  });

  final byCat = <String, List<Map<String, dynamic>>>{};
  for (final c in cases) {
    byCat.putIfAbsent(c['cat'] as String, () => []).add(c);
  }
  for (final entry in byCat.entries) {
    group(entry.key, () {
      var idx = 0;
      for (final c in entry.value) {
        idx++;
        final name = '#$idx ${c['expr']} [${c['angle']}/${c['precision']}${c['complex'] == true ? '/cplx' : ''}]';
        final known = c['known_issue'] == true;
        // Known engine discrepancies are skipped; run them with ACCURACY_KNOWN=1
        // (they are expected to fail until the engine is fixed).
        test(name, () => check(c),
            skip: known && !runKnown ? 'known engine issue: ${c['note']}' : false);
      }
    });
  }
}
