import 'package:flutter/material.dart';
import 'package:math_engine/math_engine.dart';

import '../l10n/generated/app_localizations.dart';
import 'math_view.dart';

/// Expandable list of worked steps generated by the engine (§95).
class StepsView extends StatefulWidget {
  const StepsView({super.key, required this.steps, this.initiallyExpanded = false});
  final List<SolutionStep> steps;
  final bool initiallyExpanded;

  @override
  State<StepsView> createState() => _StepsViewState();
}

class _StepsViewState extends State<StepsView> {
  late bool _open = widget.initiallyExpanded;

  @override
  Widget build(BuildContext context) {
    final l = AppLocalizations.of(context);
    final theme = Theme.of(context);
    return Card(
      child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [
        ListTile(
          leading: const Icon(Icons.format_list_numbered),
          title: Text(_open ? l.calcHideSteps : l.calcSteps),
          trailing: Icon(_open ? Icons.expand_less : Icons.expand_more),
          onTap: () => setState(() => _open = !_open),
        ),
        if (_open)
          Padding(
            padding: const EdgeInsets.fromLTRB(16, 0, 16, 16),
            child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
              for (var k = 0; k < widget.steps.length; k++) ...[
                Text('${k + 1}. ${widget.steps[k].description}', style: theme.textTheme.bodyMedium),
                if (widget.steps[k].latex != null)
                  Padding(
                    padding: const EdgeInsets.fromLTRB(16, 6, 0, 10),
                    child: SingleChildScrollView(
                      scrollDirection: Axis.horizontal,
                      child: MathView(widget.steps[k].latex!, style: theme.textTheme.titleMedium),
                    ),
                  ),
              ],
            ]),
          ),
      ]),
    );
  }
}
